'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { CalendarDays, CheckCircle2, Copy, QrCode, ArrowRight, Plus, ShieldCheck } from 'lucide-react';

type Department = { id: string; name: string; is_active: boolean };
type Slot = { id: string; department: string; starts_at: string; capacity: number; booked: number };
type Booking = { id: string; reference: string; public_key: string; starts_at: string; department: string; status: string };
type Kiosk = { id: string; department: string; public_key: string; expires_at: string };
const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Colombo' });
const clock = (date: string) => new Date(date).toLocaleTimeString('en-GB', { timeZone: 'Asia/Colombo', hour: '2-digit', minute: '2-digit' });
async function request<T>(path: string, method = 'GET', body?: unknown): Promise<T> {
 const response = await fetch('/api/service/' + path, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' });
 const result = await response.json();
 if (!response.ok) throw new Error(typeof result.detail === 'string' ? result.detail : 'Check the form values and try again.');
 return result;
}

export function CheckinQr({ tokenKey, title }: { tokenKey: string; title: string }) {
 const [origin, setOrigin] = useState('');
 const [message, setMessage] = useState('');
 useEffect(() => { setOrigin(window.location.origin); setMessage(''); }, [tokenKey]);
 const path = '/self-checkin/' + tokenKey;
 return <div className="arrival-qr"><div className="qr-image">{origin && <img width={190} height={190} src={'/api/service/self-checkin/' + tokenKey + '/qr?origin=' + encodeURIComponent(origin)} alt={'Check-in QR for ' + title}/>}</div><div><span className="section-label">SCAN. ARRIVE. RELAX.</span><h3>{title}</h3><p>Scan with your phone camera to open self check-in.</p><div className="button-row"><Link className="outline" href={path} target="_blank">Open check-in <ArrowRight size={15}/></Link><button className="outline" onClick={async () => { try { await navigator.clipboard.writeText(origin + path); setMessage('Check-in link copied.'); } catch { setMessage('Copy the link from the address bar after opening check-in.'); } }}><Copy size={15}/>Copy link</button></div>{origin.includes('127.0.0.1') || origin.includes('localhost') ? <p className="footnote">Local demo: open on this computer. Phone scanning needs a deployed clinic URL accessible from the phone.</p> : null}<p className="footnote" role="status">{message}</p></div></div>;
}

export function Appointments({ departments }: { departments: Department[] }) {
 const [day, setDay] = useState(today);
 const [department, setDepartment] = useState('');
 const [slots, setSlots] = useState<Slot[]>([]);
 const [bookings, setBookings] = useState<Booking[]>([]);
 const [selected, setSelected] = useState<Booking | null>(null);
 const [error, setError] = useState('');
 const [notice, setNotice] = useState('');
 const [busy, setBusy] = useState(false);
 const [loading, setLoading] = useState(true);
 const [revision, setRevision] = useState(0);
 useEffect(() => { let active = true; setLoading(true); setError(''); Promise.all([
  request<Slot[]>('appointments/slots?day=' + day + (department ? '&department=' + department : '')),
  request<Booking[]>('appointments?day=' + day),
 ]).then(([available, visits]) => { if (active) { setSlots(available); setBookings(visits); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [day, department, revision]);
 const mutate = async <T,>(path: string, body?: unknown): Promise<T | null> => { setBusy(true); setError(''); setNotice(''); try { const result = await request<T>(path, 'POST', body); setRevision(n => n + 1); return result; } catch (e) { setError((e as Error).message); return null; } finally { setBusy(false); } };
 return <div className="arrival-workspace">
  <div className="arrival-intro"><CalendarDays size={24}/><div><h2>A little planning. A smoother arrival.</h2><p>30-minute arrival slots · Asia/Colombo · Synthetic bookings, no patient details required.</p></div></div>
  {error && <p className="product-error" role="alert">{error}</p>}{notice && <p className="product-notice" role="status">{notice}</p>}
  <div className="filter-row"><label className="product-field"><span>Appointment date</span><input aria-label="Appointment date" type="date" required value={day} onChange={e => { if (e.target.value) setDay(e.target.value); }}/></label><label className="product-field"><span>Department</span><select aria-label="Appointment department filter" value={department} onChange={e => setDepartment(e.target.value)}><option value="">All departments</option>{departments.filter(d => d.is_active).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="outline" disabled={loading} onClick={() => setRevision(n => n + 1)}>Refresh appointments</button></div>
  <div className="two-column"><section className="panel padded"><div className="panel-heading"><h2>Available arrival slots</h2><span className="quiet">{slots.length} slots</span></div>{loading ? <p role="status">Loading slots…</p> : slots.map(slot => { const full = slot.booked >= slot.capacity; const past = new Date(slot.starts_at).getTime() <= Date.now(); return <article className="appointment-slot" key={slot.id}><div className="slot-time">{clock(slot.starts_at)}<small>30 min</small></div><div><strong>{slot.department}</strong><p>{slot.capacity - slot.booked} of {slot.capacity} places available</p></div><button className="solid" disabled={busy || full || past} onClick={async () => { const result = await mutate<Booking>('appointments', { slot_id: slot.id }); if (result) { setSelected({ ...result, starts_at: slot.starts_at, department: slot.department }); setNotice('Appointment booked. Share the private QR link with this patient.'); } }}>{past ? 'Started' : full ? 'Full' : 'Book slot'}</button></article>; })}{!loading && !slots.length && <div className="empty"><CalendarDays size={30}/><p>No slots on this date. Publish an arrival slot to begin.</p></div>}</section>
  <form className="panel padded" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); const result = await mutate('appointments/slots', { department_id: values.get('department_id'), starts_at: values.get('date') + 'T' + values.get('time') + ':00+05:30', capacity: Number(values.get('capacity')) }); if (result) { setDay(String(values.get('date'))); setDepartment(''); setNotice('Arrival slot published.'); } }}><span className="form-icon"><Plus size={22}/></span><h2>Publish an arrival slot</h2><p className="quiet">Set the number of arrivals reception can accept. Slots do not reserve clinician time or guarantee service starts at the booked time.</p><label className="product-field"><span>Department</span><select aria-label="Slot department" name="department_id" required defaultValue=""><option value="" disabled>Choose department</option>{departments.filter(d => d.is_active).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="slot-form-row"><label className="product-field"><span>Date</span><input aria-label="Slot date" name="date" type="date" min={today()} required defaultValue={day} key={day}/></label><label className="product-field"><span>Time · Colombo</span><select aria-label="Slot time" name="time" defaultValue="09:00">{Array.from({ length: 48 }, (_, i) => `${String(Math.floor(i / 2)).padStart(2, '0')}:${i % 2 ? '30' : '00'}`).map(t => <option key={t}>{t}</option>)}</select></label></div><label className="product-field"><span>Arrival capacity</span><input aria-label="Arrival capacity" name="capacity" type="number" min={1} max={20} defaultValue={2} required/></label><button className="solid" disabled={busy}>Publish slot <ArrowRight size={16}/></button></form></div>
  {selected && <section className="panel padded"><div className="panel-heading"><h2>Appointment ready</h2><button className="outline" onClick={() => setSelected(null)}>Dismiss QR</button></div><CheckinQr tokenKey={selected.public_key} title={selected.reference}/><p className="footnote">Check-in opens 30 minutes before {new Date(selected.starts_at).toLocaleString('en-GB', { timeZone: 'Asia/Colombo' })} and closes 30 minutes after the slot starts. Keep this link private.</p></section>}
  <section className="panel padded"><h2>Appointments for {day}</h2><p className="quiet">Booked arrivals join the same first-in, first-out queue when they check in.</p><div className="table-scroll"><table className="product-table"><thead><tr><th>Reference</th><th>Time</th><th>Department</th><th>Status</th><th>Actions</th></tr></thead><tbody>{bookings.map(booking => <tr key={booking.id}><td><strong>{booking.reference}</strong></td><td>{clock(booking.starts_at)}</td><td>{booking.department}</td><td><span className={'status ' + (booking.status === 'checked_in' ? 'completed' : booking.status === 'booked' ? 'waiting' : 'cancelled')}>{booking.status.replaceAll('_', ' ')}</span></td><td><div className="token-actions">{booking.status !== 'cancelled' && <button onClick={() => setSelected(booking)}><QrCode size={15}/>View QR</button>}{booking.status === 'booked' && <button disabled={busy} data-intent="danger" onClick={async () => { if (await mutate('appointments/' + booking.id + '/cancel')) { if (selected?.id === booking.id) setSelected(null); setNotice('Appointment cancelled. Its place is available again.'); } }}>Cancel booking</button>}</div></td></tr>)}</tbody></table></div>{!bookings.length && !loading && <p className="empty">No appointments on this date.</p>}</section>
 </div>;
}

export function KioskCheckin({ departments }: { departments: Department[] }) {
 const [kiosks, setKiosks] = useState<Kiosk[]>([]);
 const [error, setError] = useState('');
 const [busy, setBusy] = useState(false);
 const [selected, setSelected] = useState<Kiosk | null>(null);
 const load = useCallback(async () => { setKiosks(await request<Kiosk[]>('checkin/kiosks')); }, []);
 useEffect(() => { void load().catch(e => setError(e.message)); }, [load]);
 return <section className="panel padded kiosk-panel"><div className="arrival-intro"><QrCode size={27}/><div><h2>Let arrivals check themselves in</h2><p>Generate today’s department QR. Patients scan, confirm, and receive a private queue token.</p></div></div>{error && <p className="product-error" role="alert">{error}</p>}<form className="queue-toolbar" onSubmit={async e => { e.preventDefault(); const department_id = new FormData(e.currentTarget).get('department_id'); setBusy(true); setError(''); try { const row = await request<Kiosk>('checkin/kiosks', 'POST', { department_id }); setSelected(row); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><select aria-label="Self check-in department" name="department_id" required defaultValue=""><option value="" disabled>Choose a department</option>{departments.filter(d => d.is_active).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="solid" disabled={busy}>Generate today’s QR <QrCode size={16}/></button></form>{selected && <CheckinQr tokenKey={selected.public_key} title={kiosks.find(k => k.id === selected.id)?.department ?? 'Department check-in'}/>}{kiosks.map(kiosk => <div className="config-row" key={kiosk.id}><span><strong>{kiosk.department}</strong><small> · Expires at midnight · Asia/Colombo</small></span><div className="token-actions"><button onClick={() => setSelected(kiosk)}>Show QR</button><button data-intent="danger" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await request('checkin/kiosks/' + kiosk.id + '/revoke', 'POST'); if (selected?.id === kiosk.id) setSelected(null); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>Revoke QR</button></div></div>)}<p className="footnote">No names or medical information collected. QR access can be revoked at any time.</p></section>;
}

type CheckinInfo = { kind: string; department: string; reference: string | null; starts_at: string | null; status: string; active: boolean };
export function SelfCheckin({ tokenKey }: { tokenKey: string }) {
 const [data, setData] = useState<CheckinInfo | null>(null);
 const [error, setError] = useState('');
 const [busy, setBusy] = useState(false);
 const [patient, setPatient] = useState('');
 const [requestId, setRequestId] = useState('');
 useEffect(() => { let active = true; const storageKey = 'queuesense:arrival:' + tokenKey; let id = crypto.randomUUID(); try { id = localStorage.getItem(storageKey) as typeof id || id; localStorage.setItem(storageKey, id); } catch {} setRequestId(id); request<CheckinInfo>('self-checkin/' + tokenKey).then(row => { if (active) setData(row); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [tokenKey]);
 return <main className="patient-page"><div className="patient-brand"><QrCode size={28}/>QueueSense</div><section className="patient-card self-checkin-card"><span className="section-label">YOUR ARRIVAL, MADE SIMPLE</span><h1>{patient ? 'You’re checked in.' : 'Welcome to your visit.'}</h1>{error && <p className="product-error" role="alert">{error}</p>}{patient ? <><CheckCircle2 size={42}/><p>Your token is ready. Keep your status link private.</p><Link className="solid wide" href={'/patient/' + patient}>View my token <ArrowRight size={17}/></Link></> : data ? <><h2>{data.department}</h2>{data.reference && <p className="booking-reference">{data.reference}</p>}{data.starts_at && <p>{new Date(data.starts_at).toLocaleString('en-GB', { timeZone: 'Asia/Colombo' })} · Asia/Colombo</p>}<div className="explanation"><ShieldCheck size={23}/><p>{data.kind === 'appointment' ? 'Check in from 30 minutes before until 30 minutes after your slot starts.' : 'Confirm only when you arrive at the clinic. No personal or medical details required.'}</p></div><p className="quiet">You will join the arrival queue. Your token shows the current estimated wait.</p>{!data.active || data.status === 'cancelled' ? <p className="product-error">This check-in is unavailable. Please contact reception.</p> : <button className="solid wide" disabled={busy || !requestId} onClick={async () => { setBusy(true); setError(''); try { const result = await request<{ patient_key: string }>('self-checkin/' + tokenKey, 'POST', { request_id: requestId }); setPatient(result.patient_key); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? 'Checking in…' : data.status === 'checked_in' ? 'Retrieve my token' : 'I have arrived · Check in'}<ArrowRight size={17}/></button>}</> : !error && <p role="status">Loading your check-in…</p>}<footer>Synthetic clinic demonstration · Need help? Contact reception.</footer></section></main>;
}
