'use client';
import {useEffect,useState} from 'react';
import {Activity,Clock3,CheckCircle2} from 'lucide-react';
type Status={token:string;department:string;status:string;position:number|null;estimated_wait:number|null;notice:string};
export function PatientStatus({tokenKey}:{tokenKey:string}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/service/patient/'+encodeURIComponent(tokenKey),{cache:'no-store'});const row=await r.json();if(!r.ok)throw new Error(typeof row.detail==='string'?row.detail:'Unable to load token.');if(active){setData(row);setError('');}}catch(e){if(active)setError((e as Error).message);}}void load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer);};},[tokenKey]);
 return <main className="patient-page"><div className="patient-brand"><Activity size={28}/>QueueSense</div><section className="patient-card"><p className="section-label">A CLEARER PICTURE OF YOUR WAIT</p>{error?<p className="product-error" role="alert">{error}</p>:data?<><p>{data.department}</p><h1>{data.token}</h1><span className={'status '+data.status}>{data.status.replace('_',' ')}</span>{['called','in_service'].includes(data.status)?<div className="patient-turn"><CheckCircle2 size={30}/><h2>{data.status==='called'?'It’s your turn':'Your consultation is in progress'}</h2><p>Please follow the clinic staff’s directions.</p></div>:data.status==='waiting'?<div className="patient-wait"><Clock3 size={26}/><h2>{data.estimated_wait==null?'Waiting estimate unavailable':`About ${data.estimated_wait} minutes`}</h2><p>Queue position {data.position}</p></div>:<div className="patient-wait"><h2>{data.status==='completed'?'Your visit is complete':'This token is closed'}</h2><p>Contact reception if you need help.</p></div>}<p className="footnote">{data.notice}</p></>:<p role="status">Checking your token…</p>}<footer>Updates automatically every 5 seconds.</footer></section></main>;
}
