const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = 'http://127.0.0.1:3001';
(async () => {
 const browser = await chromium.launch({ headless: true });
 try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.getByRole('radio', { name: 'Admin', exact: false }).check();
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await page.getByRole('button', { name: 'Enter admin demo' }).click();
  await page.waitForURL('**/workspace/admin');
  const api = async (path, body, method = 'POST') => {
   const response = await context.request.fetch(base + '/api/service/' + path, { method, headers: { Origin: base }, data: body });
   assert.ok(response.ok(), path + ': ' + await response.text());
   return response.json();
  };
  const code = 'E' + Array.from({ length: 7 }, () => String.fromCharCode(65 + Math.floor(Math.random() * 26))).join('');
  const dep = await api('admin/departments', { code, name: 'Arrival verification ' + code, location: 'Synthetic test clinic', queue_threshold: 15 });
  const clinician = await api('admin/staff', { department_id: dep.id, display_name: 'Arrival verification clinician' });
  await api('staff/' + clinician.id + '/availability', { status: 'available' }, 'PATCH');
  await page.goto(base + '/workspace/admin?view=appointments');
  await page.getByRole('heading', { name: 'Publish an arrival slot' }).waitFor();
  const local = new Date(Date.now() + 330 * 60000);
  local.setUTCMinutes(local.getUTCMinutes() < 30 ? 30 : 60, 0, 0);
  const day = local.toISOString().slice(0, 10);
  const time = local.toISOString().slice(11, 16);
  await page.getByLabel('Slot department', { exact: true }).selectOption(dep.id);
  await page.getByLabel('Slot date', { exact: true }).fill(day);
  await page.getByLabel('Slot time', { exact: true }).selectOption(time);
  await page.getByLabel('Arrival capacity').fill('1');
  await page.getByRole('button', { name: 'Publish slot', exact: false }).click();
  await page.getByText('Arrival slot published.', { exact: true }).waitFor();
  const slot = page.locator('.appointment-slot').filter({ hasText: dep.name });
  await slot.getByRole('button', { name: 'Book slot', exact: true }).click();
  await page.getByRole('heading', { name: 'Appointment ready', exact: true }).waitFor();
  await slot.getByRole('button', { name: 'Full', exact: true }).waitFor();
  const href = await page.getByRole('link', { name: 'Open check-in', exact: false }).getAttribute('href');
  await page.locator('.qr-image img').evaluate(img => img.decode());
  const visitorContext = await browser.newContext();
  const visitor = await visitorContext.newPage();
  await visitor.goto(base + href);
  await visitor.getByRole('button', { name: 'I have arrived', exact: false }).waitFor();
  const queue = await context.newPage();
  await queue.goto(base + '/workspace/admin?view=live');
  await queue.getByLabel('Department', { exact: true }).selectOption(dep.id);
  await queue.getByText('● Live updates', { exact: false }).waitFor();
  const started = Date.now();
  await visitor.getByRole('button', { name: 'I have arrived', exact: false }).click();
  await visitor.getByRole('link', { name: 'View my token', exact: false }).waitFor();
  await queue.locator('tbody tr').filter({ hasText: dep.name }).waitFor({ timeout: 5000 });
  console.log('Server-pushed queue arrival visible in', Date.now() - started, 'ms');
  const patientHref = await visitor.getByRole('link', { name: 'View my token', exact: false }).getAttribute('href');
  await visitor.reload();
  await visitor.getByRole('button', { name: 'Retrieve my token', exact: false }).click();
  await visitor.getByRole('link', { name: 'View my token', exact: false }).waitFor();
  assert.equal(await visitor.getByRole('link', { name: 'View my token', exact: false }).getAttribute('href'), patientHref);
  assert.equal(await queue.locator('tbody tr').count(), 1);
  await visitor.getByRole('link', { name: 'View my token', exact: false }).click();
  await visitor.getByText('Live updates connected', { exact: true }).waitFor();
  await queue.getByLabel('Service clinician').selectOption(clinician.id);
  await queue.locator('tbody tr').getByRole('button', { name: 'Call', exact: true }).click();
  await visitor.getByRole('heading', { name: 'It’s your turn', exact: true }).waitFor({ timeout: 5000 });
  await queue.locator('tbody tr').getByRole('button', { name: 'Start service', exact: true }).click();
  await queue.locator('tbody tr').getByRole('button', { name: 'Complete', exact: true }).click();
  await visitor.getByRole('heading', { name: 'Your visit is complete', exact: true }).waitFor({ timeout: 5000 });
  await page.goto(base + '/workspace/admin?view=checkin');
  await page.getByLabel('Self check-in department').selectOption(dep.id);
  await page.getByRole('button', { name: 'Generate today’s QR', exact: false }).click();
  await page.getByRole('link', { name: 'Open check-in', exact: false }).waitFor();
  const walkinHref = await page.getByRole('link', { name: 'Open check-in', exact: false }).getAttribute('href');
  await visitor.goto(base + walkinHref);
  await visitor.getByRole('button', { name: 'I have arrived', exact: false }).click();
  await visitor.getByRole('link', { name: 'View my token', exact: false }).waitFor();
  const walkinPatient = await visitor.getByRole('link', { name: 'View my token', exact: false }).getAttribute('href');
  await visitor.reload();
  await visitor.getByRole('button', { name: 'I have arrived', exact: false }).click();
  await visitor.getByRole('link', { name: 'View my token', exact: false }).waitFor();
  assert.equal(await visitor.getByRole('link', { name: 'View my token', exact: false }).getAttribute('href'), walkinPatient);
  await page.locator('.config-row').filter({ hasText: dep.name }).getByRole('button', { name: 'Revoke QR' }).click();
  await visitor.reload();
  await visitor.getByRole('alert').filter({ hasText: 'expired' }).waitFor();
  // Close the remaining synthetic walk-in to avoid leaving active verification tokens.
  const tokens = await api('queue/live?department=' + dep.id, undefined, 'GET');
  for (const token of tokens.tokens.filter(t => t.status === 'waiting')) await api('queue/' + token.id + '/status', { status: 'cancelled' }, 'PATCH');
  await page.goto(base + '/workspace/admin?view=appointments');
  await page.getByLabel('Appointment date').fill(day);
  await page.getByLabel('Appointment department filter').selectOption(dep.id);
  for (const width of [375, 768, 1440]) {
   await page.setViewportSize({ width, height: 900 });
   assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Appointment overflow ' + width);
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.screenshot({ path: '/tmp/queuesense-appointments.png', fullPage: true });
  assert.deepEqual(errors, []);
  await visitorContext.close();
  console.log('PASS: slot publication, capacity, booking QR, anonymous idempotent arrivals, two-client queue and patient pushes, walk-in QR, revocation and responsive layouts.');
 } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
